import Menu from "@/components/menu";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.classname}
      >
                 <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Menu/>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
